services:
  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb
    ports:
      - '27017:27017'

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports:
      - '6379:6379'

networks:
  backend_network:
    driver: bridge
  cloudflare:
    external: true

volumes:
  mongodb_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
